import { pgTable, uuid, text, integer, numeric, timestamp, date, jsonb, boolean, uniqueIndex, index } from 'drizzle-orm/pg-core'

export const products = pgTable('pharmacy_products', {
  id: uuid('id').defaultRandom().primaryKey(),
  sku: text('sku').notNull(),
  barcode: text('barcode'),
  name: text('name').notNull(),
  genericName: text('generic_name'),
  brandName: text('brand_name'),
  dosage: text('dosage'),
  dosageForm: text('dosage_form'),
  strength: text('strength'),
  category: text('category').notNull(),
  reorderLevel: integer('reorder_level').notNull().default(0),
  unitOfMeasure: text('unit_of_measure').notNull().default('unit'),
  unitPrice: numeric('unit_price', { precision: 12, scale: 2 }).notNull().default('0'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({ skuIdx: uniqueIndex('pharmacy_products_sku_idx').on(table.sku), barcodeIdx: uniqueIndex('pharmacy_products_barcode_idx').on(table.barcode) }))

export const categories = pgTable('pharmacy_categories', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), description: text('description'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })
export const suppliers = pgTable('pharmacy_suppliers', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), contactName: text('contact_name'), phone: text('phone'), email: text('email'), address: text('address'), isActive: boolean('is_active').notNull().default(true), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const purchaseOrders = pgTable('pharmacy_purchase_orders', { id: uuid('id').defaultRandom().primaryKey(), orderNumber: text('order_number').notNull(), supplierId: uuid('supplier_id').notNull(), status: text('status').notNull().default('DRAFT'), orderedAt: timestamp('ordered_at', { withTimezone: true }), expectedAt: timestamp('expected_at', { withTimezone: true }), receivedAt: timestamp('received_at', { withTimezone: true }), notes: text('notes'), createdBy: text('created_by').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ orderNumberIdx: uniqueIndex('pharmacy_purchase_orders_number_idx').on(table.orderNumber), supplierIdx: index('pharmacy_purchase_orders_supplier_idx').on(table.supplierId), statusIdx: index('pharmacy_purchase_orders_status_idx').on(table.status) }))
export const purchaseOrderItems = pgTable('pharmacy_purchase_order_items', { id: uuid('id').defaultRandom().primaryKey(), purchaseOrderId: uuid('purchase_order_id').notNull(), productId: uuid('product_id').notNull(), quantityOrdered: integer('quantity_ordered').notNull(), quantityReceived: integer('quantity_received').notNull().default(0), unitCost: numeric('unit_cost', { precision: 12, scale: 2 }).notNull() }, (table) => ({ orderIdx: index('pharmacy_purchase_items_order_idx').on(table.purchaseOrderId), productIdx: index('pharmacy_purchase_items_product_idx').on(table.productId) }))
export const batches = pgTable('pharmacy_batches', { id: uuid('id').defaultRandom().primaryKey(), productId: uuid('product_id').notNull(), batchNumber: text('batch_number').notNull(), expiryDate: date('expiry_date').notNull(), manufacturedDate: date('manufactured_date'), purchasePrice: numeric('purchase_price', { precision: 12, scale: 2 }).notNull().default('0'), sellingPrice: numeric('selling_price', { precision: 12, scale: 2 }).notNull().default('0'), quantityReceived: integer('quantity_received').notNull().default(0), quantityAvailable: integer('quantity_available').notNull().default(0), supplierId: uuid('supplier_id'), receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ productIdx: index('pharmacy_batches_product_idx').on(table.productId), expiryIdx: index('pharmacy_batches_expiry_idx').on(table.expiryDate), productBatchIdx: uniqueIndex('pharmacy_batches_product_batch_idx').on(table.productId, table.batchNumber) }))
export const auditEvents = pgTable('pharmacy_audit_events', { id: uuid('id').defaultRandom().primaryKey(), actorId: text('actor_id'), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id'), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })

export const stockMovements = pgTable('pharmacy_stock_movements', { id: uuid('id').defaultRandom().primaryKey(), productId: uuid('product_id').notNull(), batchId: uuid('batch_id').notNull(), movementType: text('movement_type').notNull(), quantity: integer('quantity').notNull(), referenceType: text('reference_type'), referenceId: text('reference_id'), unitCost: numeric('unit_cost', { precision: 12, scale: 2 }), performedBy: text('performed_by'), reason: text('reason'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ batchIdx: index('pharmacy_movements_batch_idx').on(table.batchId), productIdx: index('pharmacy_movements_product_idx').on(table.productId), createdIdx: index('pharmacy_movements_created_idx').on(table.createdAt) }))
export const sales = pgTable('pharmacy_sales', { id: uuid('id').defaultRandom().primaryKey(), receiptNumber: text('receipt_number').notNull(), status: text('status').notNull().default('completed'), subtotal: numeric('subtotal', { precision: 12, scale: 2 }).notNull(), discount: numeric('discount', { precision: 12, scale: 2 }).notNull().default('0'), total: numeric('total', { precision: 12, scale: 2 }).notNull(), paymentMethod: text('payment_method').notNull(), cashierId: text('cashier_id'), idempotencyKey: text('idempotency_key').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ idempotencyIdx: uniqueIndex('pharmacy_sales_idempotency_idx').on(table.idempotencyKey) }))
export const saleLines = pgTable('pharmacy_sale_lines', { id: uuid('id').defaultRandom().primaryKey(), saleId: uuid('sale_id').notNull(), productId: uuid('product_id').notNull(), batchId: uuid('batch_id').notNull(), quantity: integer('quantity').notNull(), returnedQuantity: integer('returned_quantity').notNull().default(0), unitPrice: numeric('unit_price', { precision: 12, scale: 2 }).notNull(), lineTotal: numeric('line_total', { precision: 12, scale: 2 }).notNull() })
export const expenses = pgTable('pharmacy_expenses', { id: uuid('id').defaultRandom().primaryKey(), category: text('category').notNull(), description: text('description').notNull(), amount: numeric('amount', { precision: 12, scale: 2 }).notNull(), expenseDate: date('expense_date').notNull(), status: text('status').notNull().default('posted'), actorId: text('actor_id'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })
export const notifications = pgTable('pharmacy_notifications', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), title: text('title').notNull(), message: text('message').notNull(), severity: text('severity').notNull().default('info'), readAt: timestamp('read_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ userIdx: index('pharmacy_notifications_user_idx').on(table.userId), unreadIdx: index('pharmacy_notifications_unread_idx').on(table.userId, table.readAt) }))
export const userRoles = pgTable('pharmacy_user_roles', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), role: text('role').notNull(), accessLevel: text('access_level').notNull().default('limited'), status: text('status').notNull().default('pending'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ userIdx: uniqueIndex('pharmacy_user_roles_user_idx').on(table.userId) }))
export const settings = pgTable('pharmacy_settings', { key: text('key').primaryKey(), value: jsonb('value').notNull().default({}), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const userProfiles = pgTable('pharmacy_user_profiles', { userId: text('user_id').primaryKey(), displayName: text('display_name').notNull(), phone: text('phone'), jobTitle: text('job_title'), avatarUrl: text('avatar_url'), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })

export type Product = typeof products.$inferSelect
export type Batch = typeof batches.$inferSelect
export type Sale = typeof sales.$inferSelect
