'use client'

import { useMemo, useState } from 'react'
import { markNotificationRead, updateUserRole } from '@/app/actions/pharmacy'

type RoleRow = { id: string; userId: string; role: string; accessLevel: string; status: string; createdAt: Date | string }
type AuditRow = { id: string; actorId: string; action: string; entityType: string; entityId: string | null; createdAt: Date | string }
type NotificationRow = { id: string; title: string; message: string; readAt: Date | string | null; createdAt: Date | string }
type Report = { sales: { total: string; status: string }[]; expenses: { amount: string; status: string }[]; metrics: { salesToday: number; inventoryValue: number; lowStock: number; expiringSoon: number } }
const money = (value: number) => new Intl.NumberFormat('en-GH', { style: 'currency', currency: 'GHS' }).format(value)
const date = (value: Date | string) => new Date(value).toLocaleString('en-GH', { dateStyle: 'medium', timeStyle: 'short' })

export function AdminWorkspace({ active, roles = [], audit = [], notifications = [], report, onNotify }: { active: string; roles?: RoleRow[]; audit?: AuditRow[]; notifications?: NotificationRow[]; report?: Report; onNotify: (message: string) => void }) {
  if (active === 'Users & roles') return <UsersRoles roles={roles} onNotify={onNotify} />
  if (active === 'Audit log') return <AuditLog rows={audit} />
  if (active === 'Notifications') return <Notifications rows={notifications} onNotify={onNotify} />
  if (active === 'Reports') return <Reports report={report} />
  return null
}
function UsersRoles({ roles, onNotify }: { roles: RoleRow[]; onNotify: (message: string) => void }) {
  const [query, setQuery] = useState('')
  const [saving, setSaving] = useState<string | null>(null)
  const visible = roles.filter((row) => `${row.userId} ${row.role} ${row.status}`.toLowerCase().includes(query.toLowerCase()))
  const save = async (row: RoleRow, status: string) => { setSaving(row.id); try { await updateUserRole({ userId: row.userId, role: row.role, accessLevel: row.accessLevel, status }); onNotify(`Access ${status}`) } catch (error) { onNotify(error instanceof Error ? error.message : 'Unable to update access') } finally { setSaving(null) } }
  return <div className="mt-5 space-y-4"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by user or role" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-sky-500" /><div className="overflow-x-auto rounded-xl border border-slate-100"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">User</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Access</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((row) => <tr key={row.id}><td className="px-4 py-3 font-medium text-slate-800">{row.userId}</td><td className="px-4 py-3 capitalize">{row.role.replace('_', ' ')}</td><td className="px-4 py-3 capitalize">{row.accessLevel}</td><td className="px-4 py-3"><span className="rounded-full bg-amber-50 px-2 py-1 capitalize text-amber-700">{row.status}</span></td><td className="px-4 py-3"><button disabled={saving === row.id} onClick={() => save(row, row.status === 'active' ? 'suspended' : 'active')} className="rounded-lg border border-slate-200 px-3 py-1.5 font-semibold text-sky-700 disabled:opacity-50">{row.status === 'active' ? 'Suspend' : 'Approve'}</button></td></tr>)}</tbody></table>{!visible.length && <p className="p-6 text-center text-sm text-slate-500">No role assignments found.</p>}</div></div>
}
function AuditLog({ rows }: { rows: AuditRow[] }) { return <div className="mt-5 overflow-x-auto rounded-xl border border-slate-100"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">When</th><th className="px-4 py-3">Action</th><th className="px-4 py-3">Entity</th><th className="px-4 py-3">Actor</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id}><td className="px-4 py-3 text-slate-500">{date(row.createdAt)}</td><td className="px-4 py-3 font-semibold capitalize text-slate-800">{row.action}</td><td className="px-4 py-3">{row.entityType} {row.entityId ? `· ${row.entityId.slice(0, 8)}` : ''}</td><td className="px-4 py-3 text-slate-500">{row.actorId}</td></tr>)}</tbody></table>{!rows.length && <p className="p-6 text-center text-sm text-slate-500">No audit events found.</p>}</div> }
function Notifications({ rows: initial, onNotify }: { rows: NotificationRow[]; onNotify: (message: string) => void }) { const [rows, setRows] = useState(initial); const unread = rows.filter((row) => !row.readAt).length; const read = async (id: string) => { await markNotificationRead(id); setRows((items) => items.map((row) => row.id === id ? { ...row, readAt: new Date() } : row)); onNotify('Notification marked as read') }; return <div className="mt-5 space-y-3"><p className="text-sm text-slate-500">{unread} unread notification{unread === 1 ? '' : 's'}</p>{rows.map((row) => <article key={row.id} className={`rounded-xl border p-4 ${row.readAt ? 'border-slate-100 bg-white' : 'border-sky-100 bg-sky-50/60'}`}><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-slate-800">{row.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{row.message}</p><p className="mt-2 text-[10px] text-slate-400">{date(row.createdAt)}</p></div>{!row.readAt && <button onClick={() => read(row.id)} className="shrink-0 rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-sky-700">Mark read</button>}</div></article>)}{!rows.length && <p className="rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">You are all caught up.</p>}</div> }
function Reports({ report }: { report?: Report }) { const sales = report?.sales.filter((row) => row.status !== 'voided').reduce((sum, row) => sum + Number(row.total), 0) ?? 0; const expenses = report?.expenses.filter((row) => row.status !== 'voided').reduce((sum, row) => sum + Number(row.amount), 0) ?? 0; return <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-xl bg-emerald-50 p-4"><p className="text-xs text-slate-500">Sales loaded</p><p className="mt-1 text-xl font-bold text-slate-900">{money(sales)}</p></div><div className="rounded-xl bg-rose-50 p-4"><p className="text-xs text-slate-500">Expenses loaded</p><p className="mt-1 text-xl font-bold text-slate-900">{money(expenses)}</p></div><div className="rounded-xl bg-sky-50 p-4"><p className="text-xs text-slate-500">Inventory value</p><p className="mt-1 text-xl font-bold text-slate-900">{money(report?.metrics.inventoryValue ?? 0)}</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-xs text-slate-500">Net movement</p><p className="mt-1 text-xl font-bold text-slate-900">{money(sales - expenses)}</p></div></div> }
