import { z } from 'zod'

export const productInput = z.object({ name: z.string().trim().min(2).max(120), sku: z.string().trim().min(2).max(40).regex(/^[A-Z0-9-]+$/), category: z.string().trim().min(2).max(80), unitPrice: z.coerce.number().nonnegative(), reorderLevel: z.coerce.number().int().nonnegative(), isControlled: z.coerce.boolean().default(false) })
export const batchInput = z.object({ productId: z.string().uuid(), batchNumber: z.string().trim().min(1).max(100), manufacturedDate: z.string().date().optional(), expiryDate: z.string().date(), quantity: z.coerce.number().int().nonnegative(), costPrice: z.coerce.number().nonnegative(), sellingPrice: z.coerce.number().nonnegative().optional(), supplierId: z.string().uuid().optional() }).superRefine((value, ctx) => { if (value.manufacturedDate && value.manufacturedDate > value.expiryDate) ctx.addIssue({ code: 'custom', path: ['manufacturedDate'], message: 'Manufactured date cannot be after expiry date' }) })
export const expenseInput = z.object({ category: z.string().trim().min(2).max(60), description: z.string().trim().min(2).max(240), amount: z.coerce.number().positive(), expenseDate: z.string().date() })
export const checkoutInput = z.object({ items: z.array(z.object({ productId: z.string().uuid(), quantity: z.coerce.number().int().positive() })).min(1), paymentMethod: z.enum(['cash', 'card', 'transfer']), idempotencyKey: z.string().min(12).max(120) })
export const purchaseOrderInput = z.object({ supplierId: z.string().uuid(), expectedAt: z.string().datetime().optional(), notes: z.string().max(500).optional(), items: z.array(z.object({ productId: z.string().uuid(), quantityOrdered: z.coerce.number().int().positive(), unitCost: z.coerce.number().nonnegative() })).min(1) })
export const receivePurchaseInput = z.object({ items: z.array(z.object({ purchaseOrderItemId: z.string().uuid(), batchNumber: z.string().trim().min(1).max(100), expiryDate: z.string().date(), manufacturedDate: z.string().date().optional(), quantity: z.coerce.number().int().positive(), sellingPrice: z.coerce.number().nonnegative() })).min(1) }).superRefine((value, ctx) => value.items.forEach((item, index) => { if (item.manufacturedDate && item.manufacturedDate > item.expiryDate) ctx.addIssue({ code: 'custom', path: ['items', index, 'manufacturedDate'], message: 'Manufactured date cannot be after expiry date' }) }))
export const profileInput = z.object({ displayName: z.string().trim().min(2).max(100), phone: z.string().trim().max(30).optional(), jobTitle: z.string().trim().max(80).optional() })
export const accessRequestInput = z.object({ role: z.enum(['pharmacist', 'cashier', 'stock_manager']), accessLevel: z.enum(['limited', 'standard', 'full']) })
export const settingInput = z.object({ key: z.enum(['pharmacy_name', 'pharmacy_phone', 'tax_rate', 'default_discount', 'low_stock_threshold', 'expiry_alert_days', 'receipt_footer']), value: z.union([z.string().trim().max(500), z.number().finite().min(0).max(100), z.boolean()]) })
export const stockAdjustmentInput = z.object({ productId: z.string().uuid(), batchId: z.string().uuid(), quantity: z.coerce.number().int().refine((value) => value !== 0), reason: z.string().trim().min(3).max(240) })
export const returnInput = z.object({ saleId: z.string().uuid(), lines: z.array(z.object({ saleLineId: z.string().uuid(), quantity: z.coerce.number().int().positive() })).min(1), reason: z.string().trim().min(3).max(240), refundMethod: z.enum(['cash', 'card', 'transfer']).default('cash') })
